patch:
  key_binder:
    bindings:
      - {accept: minus, send: Page_Up, when: has_menu}
      - {accept: equal, send: Page_Down, when: has_menu}
      - {accept: comma, send: Page_Up, when: paging}
      - {accept: period, send: Page_Down, when: paging}
      - {accept: "Control+Alt+f", toggle: full_shape, when: always}
      - {accept: "Control+period", toggle: ascii_punct, when: always}
  punctuator:
    full_shape:
      " ": {commit: "　"}
      "!": {commit: "！"}
      "\"": {pair: ["“", "”"]}
      "#": ["＃", "⌘"]
      "$": ["￥", "$", "€", "£", "¥", "¢", "¤"]
      "%": ["％", "°", "℃"]
      "&": "＆"
      "'": {pair: ["‘", "’"]}
      "(": "（"
      ")": "）"
      "*": ["＊", "·", "・", "×", "※", "❂"]
      "+": "＋"
      ",": {commit: "，"}
      "-": "－"
      ".": {commit: "。"}
      "/": "、"
      ":": {commit: "："}
      ";": {commit: "；"}
      "<": ["《", "〈", "«", "‹"]
      "=": "＝"
      ">": ["》", "〉", "»", "›"]
      "?": {commit: "？"}
      "@": ["＠", "☯"]
      "[": ["「", "【", "〔", "［"]
      "\\": ["、", "＼"]
      "]": ["」", "】", "〕", "］"]
      "^": {commit: "……"}
      "_": "——"
      "`": "｀"
      "{": ["『", "〖", "｛"]
      "|": ["·", "｜", "§", "¦"]
      "}": ["』", "〗", "｝"]
      "~": "～"
    half_shape:
      "`": "`"
      "~": ["~", "～"]
      "!": "!"
      "@": "@"
      "#": "#"
      "$": ["￥", "$"]
      "%": ["%", "％"]
      "^": {commit: "..."}
      "&": "&"
      "*": ["★", "☆"]
      "(": "（"
      ")": "）"
      "-": "-"
      "=": "="
      "[": "["
      "]": "]"
      "\\": {pair: ["【", "】"]}
      ";": {commit: "、"}
      "'": {pair: ["「", "」"]}
      ",": {commit: "，"}
      ".": {commit: "。"}
      "/": "/"
      "_": "_"
      "+": "+"
      "{": ["｛", "〔", "［"]
      "}": ["｝", "〕", "］"]
      "|": {pair: ["〖", "〗"]}
      ":": {commit: "："}
      "\"": {pair: ["『", "』"]}
      "<": "«"
      ">": "»"
      "?": {commit: "？"}
