patch:
  schema_list:
    - schema: cqlb_fluency
    - schema: cqlb_express
  key_binder:
    bindings:
      - {accept: Return, send: "Control+Return", when: composing}
      - {accept: 9, send: Page_Up, when: has_menu}
      - {accept: 0, send: Page_Down, when: has_menu}
      - {accept: 9, send: Page_Up, when: paging}
      - {accept: 0, send: Page_Down, when: paging}
      - {accept: "Control+Alt+f", toggle: traditional, when: always}
      - {accept: "Control+period", toggle: ascii_punct, when: always}
      - {accept: "Control+Alt+period", toggle: full_shape, when: always}
  punctuator:
    full_shape:
      " ": {commit: "　"}
    half_shape:
      "`": "`"
      "~": ["～", "~"]
      "!": "!"
      "@": "@"
      "#": "#"
      "$": ["￥", "$"]
      "%": ["％", "%"]
      "^": ["……", "——"]
      "&": "&"
      "*": ["★", "☆", "※"]
      "(": {commit: "（"}
      ")": {commit: "）"}
      "-": "-"
      "=": "="
      "[": "["
      "]": "]"
      "\\": {pair: ["【", "】"]}
      ";": {commit: "、"}
      "'": {pair: ["「", "」"]}
      ",": {commit: "，"}
      ".": {commit: "。"}
      "/": "/"
      "_": "_"
      "+": "+"
      "{": ["｛", "〔", "［"]
      "}": ["｝", "〕", "］"]
      "|": {pair: ["〖", "〗"]}
      ":": {commit: "："}
      "\"": {pair: ["『", "』"]}
      "<": {commit: "《"}
      ">": {commit: "》"}
      "?": {commit: "？"}
  switcher:
    hotkeys:
      - "Control+grave"
      - "Control+Shift+grave"
  ascii_composer/switch_key:
    Shift_L: commit_code
