patch:
  schema_list:
    - schema: cqlb_express
  key_binder:
    bindings:
      - { accept: Tab,                send: Shift+Right,    when: composing }
      - { accept: Shift+Tab,          send: Shift+Left,     when: composing }
      - { accept: minus,              send: Page_Up,        when: has_menu  }
      - { accept: equal,              send: Page_Down,      when: has_menu  }
      - { accept: comma,              send: Page_Up,        when: paging    }
      - { accept: period,             send: Page_Down,      when: paging    }
      - { accept: Control+slash,      toggle: traditional,  when: always    }
      - { accept: Control+comma,      toggle: full_shape,   when: always    }
      - { accept: Control+period,     toggle: ascii_punct,  when: always    }
      - { accept: Control+semicolon,  toggle: ascii_mode,   when: always    }
  ascii_composer/switch_key:
    Shift_L: commit_text
  punctuator:
    full_shape:
      " ": {commit: "　"}
    half_shape:
      "`": "`"
      "~": ["~", "～"]
      "!": "!"
      "@": "@"
      "#": "#"
      "$": ["￥", "$"]
      "%": ["%", "％"]
      "^": {commit: "..."}
      "&": "&"
      "*": ["★", "☆"]
      "(": "（"
      ")": "）"
      "-": "-"
      "=": "="
      "[": "["
      "]": "]"
      "\\": {pair: ["【", "】"]}
      ";": {commit: "、"}
      "'": {pair: ["「", "」"]}
      ",": {commit: "，"}
      ".": {commit: "。"}
      "/": "/"
      "_": "_"
      "+": "+"
      "{": ["｛", "〔", "［"]
      "}": ["｝", "〕", "］"]
      "|": {pair: ["〖", "〗"]}
      ":": {commit: "："}
      "\"": {pair: ["『", "』"]}
      "<": "«"
      ">": "»"
      "?": {commit: "？"}
