--- 
- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:/sun/maildir/company
  usual: true
  archived: false
  id: 1
  labels: []

- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:/sun/maildir/sent
  usual: false
  archived: false
  id: 2
  labels: []

